/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author eruma
 */
public class CreateAutoNuevo extends javax.swing.JFrame {

    /**
     * Creates new form CreateAutoNuevo
     */
    public CreateAutoNuevo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtFieldModelo = new javax.swing.JTextField();
        txtFieldLinea = new javax.swing.JTextField();
        txtFieldNumSerie = new javax.swing.JTextField();
        txtFieldColor = new javax.swing.JTextField();
        txtFieldMarca = new javax.swing.JTextField();
        btnSig = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFieldModelo.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        txtFieldModelo.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldModelo.setText("Modelo");
        txtFieldModelo.setBorder(null);
        txtFieldModelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldModeloFocusLost(evt);
            }
        });
        txtFieldModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFieldModeloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFieldModeloMouseExited(evt);
            }
        });
        txtFieldModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldModeloActionPerformed(evt);
            }
        });
        txtFieldModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldModeloKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldModeloKeyTyped(evt);
            }
        });
        jPanel1.add(txtFieldModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 650, 30));

        txtFieldLinea.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        txtFieldLinea.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldLinea.setText("Línea");
        txtFieldLinea.setBorder(null);
        txtFieldLinea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldLineaFocusLost(evt);
            }
        });
        txtFieldLinea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFieldLineaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFieldLineaMouseExited(evt);
            }
        });
        txtFieldLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldLineaActionPerformed(evt);
            }
        });
        txtFieldLinea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldLineaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldLineaKeyTyped(evt);
            }
        });
        jPanel1.add(txtFieldLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 650, 30));

        txtFieldNumSerie.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        txtFieldNumSerie.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldNumSerie.setText("Num. Serie");
        txtFieldNumSerie.setBorder(null);
        txtFieldNumSerie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldNumSerieFocusLost(evt);
            }
        });
        txtFieldNumSerie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFieldNumSerieMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFieldNumSerieMouseExited(evt);
            }
        });
        txtFieldNumSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNumSerieActionPerformed(evt);
            }
        });
        txtFieldNumSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldNumSerieKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldNumSerieKeyTyped(evt);
            }
        });
        jPanel1.add(txtFieldNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 650, 30));

        txtFieldColor.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        txtFieldColor.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldColor.setText("Color");
        txtFieldColor.setBorder(null);
        txtFieldColor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldColorFocusLost(evt);
            }
        });
        txtFieldColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFieldColorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFieldColorMouseExited(evt);
            }
        });
        txtFieldColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldColorActionPerformed(evt);
            }
        });
        txtFieldColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldColorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldColorKeyTyped(evt);
            }
        });
        jPanel1.add(txtFieldColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 650, 30));

        txtFieldMarca.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        txtFieldMarca.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldMarca.setText("Marca");
        txtFieldMarca.setBorder(null);
        txtFieldMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldMarcaFocusLost(evt);
            }
        });
        txtFieldMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFieldMarcaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFieldMarcaMouseExited(evt);
            }
        });
        txtFieldMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldMarcaActionPerformed(evt);
            }
        });
        txtFieldMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldMarcaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldMarcaKeyTyped(evt);
            }
        });
        jPanel1.add(txtFieldMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 650, 30));

        btnSig.setForeground(new java.awt.Color(51, 51, 51));
        btnSig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSelectPersona/btnSig.png"))); // NOI18N
        btnSig.setBorder(null);
        btnSig.setBorderPainted(false);
        btnSig.setContentAreaFilled(false);
        btnSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigActionPerformed(evt);
            }
        });
        jPanel1.add(btnSig, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, -1, -1));

        btnCancel.setForeground(new java.awt.Color(51, 51, 51));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSelectPersona/btnCancel.png"))); // NOI18N
        btnCancel.setBorder(null);
        btnCancel.setBorderPainted(false);
        btnCancel.setContentAreaFilled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCreateAutoNuevo/fondo.png"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigActionPerformed

    }//GEN-LAST:event_btnSigActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtFieldModeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldModeloFocusLost
        if (txtFieldModelo.getText().equals("")) {
            txtFieldModelo.setText("Modelo");
        }
    }//GEN-LAST:event_txtFieldModeloFocusLost

    private void txtFieldModeloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldModeloMouseEntered
        if (txtFieldModelo.getText().equals("Modelo"))
        txtFieldModelo.setText("");
    }//GEN-LAST:event_txtFieldModeloMouseEntered

    private void txtFieldModeloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldModeloMouseExited
        if (txtFieldModelo.getText().equals("")) {
            txtFieldModelo.setText("Modelo");
        } else if (!txtFieldModelo.getText().equals("Modelo")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFieldModeloMouseExited

    private void txtFieldModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldModeloActionPerformed

    }//GEN-LAST:event_txtFieldModeloActionPerformed

    private void txtFieldModeloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldModeloKeyReleased
        // TODO add your handling code here:
        txtFieldModelo.setText(txtFieldModelo.getText().trim());
    }//GEN-LAST:event_txtFieldModeloKeyReleased

    private void txtFieldModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldModeloKeyTyped
        txtFieldModelo.setText(txtFieldModelo.getText().trim());
        if (txtFieldModelo.getText().equals("Modelo")) {
            txtFieldModelo.setText("");
        }
    }//GEN-LAST:event_txtFieldModeloKeyTyped

    private void txtFieldLineaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldLineaFocusLost
        if (txtFieldLinea.getText().equals("")) {
            txtFieldLinea.setText("Línea");
        }
    }//GEN-LAST:event_txtFieldLineaFocusLost

    private void txtFieldLineaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldLineaMouseEntered
        if (txtFieldLinea.getText().equals("Línea"))
        txtFieldLinea.setText("");
    }//GEN-LAST:event_txtFieldLineaMouseEntered

    private void txtFieldLineaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldLineaMouseExited
        if (txtFieldLinea.getText().equals("")) {
            txtFieldLinea.setText("Línea");
        } else if (!txtFieldLinea.getText().equals("Línea")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFieldLineaMouseExited

    private void txtFieldLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldLineaActionPerformed

    }//GEN-LAST:event_txtFieldLineaActionPerformed

    private void txtFieldLineaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldLineaKeyReleased
        // TODO add your handling code here:
        txtFieldLinea.setText(txtFieldLinea.getText().trim());
    }//GEN-LAST:event_txtFieldLineaKeyReleased

    private void txtFieldLineaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldLineaKeyTyped
        txtFieldLinea.setText(txtFieldLinea.getText().trim());
        if (txtFieldLinea.getText().equals("Línea")) {
            txtFieldLinea.setText("");
        }
    }//GEN-LAST:event_txtFieldLineaKeyTyped

    private void txtFieldNumSerieFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldNumSerieFocusLost
        if (txtFieldNumSerie.getText().equals("")) {
            txtFieldNumSerie.setText("Num. Serie");
        }
    }//GEN-LAST:event_txtFieldNumSerieFocusLost

    private void txtFieldNumSerieMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldNumSerieMouseEntered
        if (txtFieldNumSerie.getText().equals("Num. Serie"))
        txtFieldNumSerie.setText("");
    }//GEN-LAST:event_txtFieldNumSerieMouseEntered

    private void txtFieldNumSerieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldNumSerieMouseExited
        if (txtFieldNumSerie.getText().equals("")) {
            txtFieldNumSerie.setText("Num. Serie");
        } else if (!txtFieldNumSerie.getText().equals("Num. Serie")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFieldNumSerieMouseExited

    private void txtFieldNumSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNumSerieActionPerformed

    }//GEN-LAST:event_txtFieldNumSerieActionPerformed

    private void txtFieldNumSerieKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldNumSerieKeyReleased
        // TODO add your handling code here:
        txtFieldNumSerie.setText(txtFieldNumSerie.getText().trim());
    }//GEN-LAST:event_txtFieldNumSerieKeyReleased

    private void txtFieldNumSerieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldNumSerieKeyTyped
        txtFieldNumSerie.setText(txtFieldNumSerie.getText().trim());
        if (txtFieldNumSerie.getText().equals("Num. Serie")) {
            txtFieldNumSerie.setText("");
        }
    }//GEN-LAST:event_txtFieldNumSerieKeyTyped

    private void txtFieldColorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldColorFocusLost
        if (txtFieldColor.getText().equals("")) {
            txtFieldColor.setText("Color");
        }
    }//GEN-LAST:event_txtFieldColorFocusLost

    private void txtFieldColorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldColorMouseEntered
        if (txtFieldColor.getText().equals("Color"))
        txtFieldColor.setText("");
    }//GEN-LAST:event_txtFieldColorMouseEntered

    private void txtFieldColorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldColorMouseExited
        if (txtFieldColor.getText().equals("")) {
            txtFieldColor.setText("Color");
        } else if (!txtFieldColor.getText().equals("Color")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFieldColorMouseExited

    private void txtFieldColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldColorActionPerformed

    }//GEN-LAST:event_txtFieldColorActionPerformed

    private void txtFieldColorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldColorKeyReleased
        // TODO add your handling code here:
        txtFieldColor.setText(txtFieldColor.getText().trim());
    }//GEN-LAST:event_txtFieldColorKeyReleased

    private void txtFieldColorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldColorKeyTyped
        txtFieldColor.setText(txtFieldColor.getText().trim());
        if (txtFieldColor.getText().equals("Color")) {
            txtFieldColor.setText("");
        }
    }//GEN-LAST:event_txtFieldColorKeyTyped

    private void txtFieldMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldMarcaFocusLost
        if (txtFieldMarca.getText().equals("")) {
            txtFieldMarca.setText("Marca");
        }
    }//GEN-LAST:event_txtFieldMarcaFocusLost

    private void txtFieldMarcaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldMarcaMouseEntered
        if (txtFieldMarca.getText().equals("Marca"))
        txtFieldMarca.setText("");
    }//GEN-LAST:event_txtFieldMarcaMouseEntered

    private void txtFieldMarcaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldMarcaMouseExited
        if (txtFieldMarca.getText().equals("")) {
            txtFieldMarca.setText("Marca");
        } else if (!txtFieldMarca.getText().equals("Marca")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFieldMarcaMouseExited

    private void txtFieldMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldMarcaActionPerformed

    }//GEN-LAST:event_txtFieldMarcaActionPerformed

    private void txtFieldMarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldMarcaKeyReleased
        // TODO add your handling code here:
        txtFieldMarca.setText(txtFieldMarca.getText().trim());
    }//GEN-LAST:event_txtFieldMarcaKeyReleased

    private void txtFieldMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldMarcaKeyTyped
        txtFieldMarca.setText(txtFieldMarca.getText().trim());
        if (txtFieldMarca.getText().equals("Marca")) {
            txtFieldMarca.setText("");
        }
    }//GEN-LAST:event_txtFieldMarcaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAutoNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAutoNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAutoNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAutoNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAutoNuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSig;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtFieldColor;
    private javax.swing.JTextField txtFieldLinea;
    private javax.swing.JTextField txtFieldMarca;
    private javax.swing.JTextField txtFieldModelo;
    private javax.swing.JTextField txtFieldNumSerie;
    // End of variables declaration//GEN-END:variables
}
