/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import implementaciones.PersonaDAO;
import interfaces.IConexionBD;
import interfaces.IPersonaDAO;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import org.itson.dominio.Persona;
import utilidades.ConstantesGUI;

/**
 *
 * @author eruma
 */
public class SelectTramite extends javax.swing.JFrame {

    private IConexionBD conexion;
    private IPersonaDAO personaDAO;
    
    /**
     * Creates new form SelectTramite
     */
    public SelectTramite(IConexionBD conexion) {
        initComponents();
        this.conexion = conexion;
        this.personaDAO = new PersonaDAO(this.conexion.crearConexion());
        this.setLocationRelativeTo(null);
    }

    private void abrirBuscadorPersonas(ConstantesGUI gui) {
        if (this.isVisible()) {
            new SelectPersona(conexion, gui).setVisible(true);
            this.setVisible(false);
        }
    }
    
    private void mostrarMensajePantalla(String msj) {
        JOptionPane.showMessageDialog(null, msj, "Info", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPlacas = new javax.swing.JButton();
        btnLicencias = new javax.swing.JButton();
        btnUserHistorial = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        lblAddCuentas = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPlacas.setForeground(new java.awt.Color(51, 51, 51));
        btnPlacas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSelectTramite/btnPlacas.png"))); // NOI18N
        btnPlacas.setBorder(null);
        btnPlacas.setBorderPainted(false);
        btnPlacas.setContentAreaFilled(false);
        btnPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlacasActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, -1, -1));

        btnLicencias.setForeground(new java.awt.Color(51, 51, 51));
        btnLicencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSelectTramite/btnLicencia.png"))); // NOI18N
        btnLicencias.setBorder(null);
        btnLicencias.setBorderPainted(false);
        btnLicencias.setContentAreaFilled(false);
        btnLicencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicenciasActionPerformed(evt);
            }
        });
        jPanel1.add(btnLicencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, -1));

        btnUserHistorial.setForeground(new java.awt.Color(51, 51, 51));
        btnUserHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSelectTramite/btnUserHistorial.png"))); // NOI18N
        btnUserHistorial.setBorder(null);
        btnUserHistorial.setBorderPainted(false);
        btnUserHistorial.setContentAreaFilled(false);
        jPanel1.add(btnUserHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        btnAddUser.setForeground(new java.awt.Color(51, 51, 51));
        btnAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSelectTramite/addUser.png"))); // NOI18N
        btnAddUser.setBorder(null);
        btnAddUser.setBorderPainted(false);
        btnAddUser.setContentAreaFilled(false);
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 570, -1, -1));

        lblAddCuentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSelectTramite/lblAgregarCuentas.png"))); // NOI18N
        jPanel1.add(lblAddCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSelectTramite/FondoBase.png"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLicenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicenciasActionPerformed
        abrirBuscadorPersonas(ConstantesGUI.LICENCIAS);
    }//GEN-LAST:event_btnLicenciasActionPerformed

    private void btnPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlacasActionPerformed
        abrirBuscadorPersonas(ConstantesGUI.PLACAS);
    }//GEN-LAST:event_btnPlacasActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        if(personaDAO.insercionMasivaPersonas()){
            mostrarMensajePantalla("Se han insertado 20 registros de Personas para pruebas");
        }else{
            mostrarMensajePantalla("Ya hay suficientes registros para pruebas");
        }
        
    }//GEN-LAST:event_btnAddUserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnLicencias;
    private javax.swing.JButton btnPlacas;
    private javax.swing.JButton btnUserHistorial;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddCuentas;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
